#!/bin/expect

set timeout 10
set PROMPT "/ #"

spawn docker run -it --rm -v /tmp/my-rootfs:/my-rootfs alpine

set f [open "./setup/docker_commands.sh"]
set commands [split [read $f] "\n"]
close $f

foreach cmd $commands {
    send "$cmd\r"
    expect "$PROMPT"
}

send "exit\r"
expect eof